coccicheck: propagate error and stop processing after first error
Propagate back in the shell Coccinelle's error. Also stop
processing if an error has occured. This lets us handle some
errors in coccinelle cocci files and if they bail out we should
inspect the errors. This will be more useful later to help annotate
coccinelle version dependency requirements.

Signed-off-by: Luis R. Rodriguez <mcgrof@kernel.org>

diff --git a/scripts/coccicheck b/scripts/coccicheck
--- a/scripts/coccicheck
+++ b/scripts/coccicheck
@@ -278,6 +278,10 @@ run_cmd_parmap() {
 		echo "Running ($NPROC in parallel): $@"
 	fi
 	$@ 2>&1
+	if [[ $? -ne 0 ]]; then
+		echo "coccicheck failed"
+		exit $?
+	fi
 }
 
 run_cmd_old() {
